oesmith/puffing-billy

README.md, lib/billy/cache.rb, lib/billy/config.rb, spec/lib/billy/cache_spec.rb
- Specifically intended to get around analytics requests with
different URLs each time, sometimes even just slightly different
hostnames!
=> Add new configuration to merge cache hits

lib/billy.rb
=> Consistently ignore SSL errors (added to selenium driver)

CHANGELOG.md, Gemfile.lock, lib/billy/handlers/cache_handler.rb, lib/billy/handlers/proxy_handler.rb, lib/billy/handlers/stub_handler.rb, lib/billy/json_utils.rb, lib/billy/proxy.rb, lib/billy/proxy_connection.rb, lib/billy/version.rb, lib/tasks/billy.rake
=> Use Addressable for all URI parsing

Gemfile.lock, lib/billy/handlers/proxy_handler.rb, spec/lib/billy/handlers/proxy_handler_spec.rb
https://github.com/oesmith/puffing-billy/pull/50
=> Add regex whitelist

CHANGELOG.md, lib/billy/version.rb
Supersedes https://github.com/oesmith/puffing-billy/pull/88
=> Support basic auth in requests

CHANGELOG.md
Make it a little easier on devs reviewing changelog to review details of changes.
=> Include links in CHANGELOG.md

lib/billy/version.rb
Supersedes https://github.com/oesmith/puffing-billy/pull/145
=> Allow Puffing Billy to run with custom host

README.md, examples/intercept_request.html, lib/billy/config.rb, lib/billy/handlers/stub_handler.rb, lib/billy/proxy_request_stub.rb, spec/features/examples/intercept_request_spec.rb, spec/lib/billy/proxy_request_stub_spec.rb
Resolved conflicts from https://github.com/oesmith/puffing-billy/pull/154
=> Make requests to stubs accessible

README.md
=> Add README status badges

lib/billy/handlers/proxy_handler.rb, spec/lib/proxy_spec.rb
Hey, would you be open to allowing Regexps in ```path_blacklist```?
=> Support using a Regexp in path_blacklist

README.md
just cucumber for the moment - hope to add RSpec in future - refactor and maybe pull into project?
=> add to README about different cache directories

README.md, lib/billy/config.rb, lib/billy/handlers/cache_handler.rb, spec/lib/billy/handlers/cache_handler_spec.rb
=> Allow to simulate network delays when responding from cache

README.md
**- What is it good for?**
More wisdom for Chrome Headless/macOS on SSL. This should also help #193 and #204 IMHO.
**- What I did**
I just added some information on the handling of valid certificates on macOS for Chrome Headless on the readme file.
**- A picture of a cute animal (not mandatory but encouraged)**
=> Updated the Chrome Headless section with more macOS wisdom

README.md
=> Add note about suppressed errors

lib/billy/init/rspec.rb
=> Prepend rspec puffing billy reset hook

lib/billy/proxy.rb, spec/spec_helper.rb
Fix for the following issue: 
https://github.com/oesmith/puffing-billy/issues/246
=> rescue on Errno::ENETUNREACH, in port_in_use? method

.travis.yml, README.md, lib/billy/browsers/capybara.rb, puffing-billy.gemspec
This PR adds a default registration for the Apparition (Chrome via CDP) driver - https://github.com/twalpole/apparition
=> Add driver registration for apparition driver

README.md
Updated Readme to cover how to append to whitelist without overriding default values.
=> Readme: How to append to whitelist without overriding.

puffing-billy.gemspec
=> Fix specs on master

README.md
I found README to be hard to follow. I tried to rearrange some sections around and clean it up a bit.
Let me know what you think.
You can preview the new README here: https://github.com/oesmith/puffing-billy/blob/85f5a8136ac2564235e97a51573c578d1760660b/README.md
=> Make README.md easier to follow

README.md
Addresses https://github.com/oesmith/puffing-billy/issues/299
=> Update resource links in README

puffing-billy.gemspec
@ronwsmith this is the patch to include rake tasks inside the gem generation.
=> Add rake tasks inside files DSL in gemspec

.github/workflows/ci.yml, .rspec, puffing-billy.gemspec, spec/lib/proxy_spec.rb
Fixed one single rspec and thin dependency
=> Support Ruby 3.2
