- Guardfile
- Rakefile
- lib/billy.rb
- lib/billy/cache.rb
- lib/billy/config.rb
- lib/billy/handlers/cache_handler.rb
- lib/billy/handlers/handler.rb
- lib/billy/handlers/proxy_handler.rb
- lib/billy/handlers/request_handler.rb
- lib/billy/handlers/stub_handler.rb
- lib/billy/json_utils.rb
- lib/billy/proxy_connection.rb
- lib/billy/proxy_request_stub.rb
- lib/billy/version.rb
- lib/tasks/billy.rake
- puffing-billy.gemspec
- spec/features/examples/facebook_api_spec.rb
- spec/features/examples/tumblr_api_spec.rb
- spec/lib/billy/cache_spec.rb
- spec/lib/billy/handlers/cache_handler_spec.rb
- spec/lib/billy/handlers/handler_spec.rb
- spec/lib/billy/handlers/proxy_handler_spec.rb
- spec/lib/billy/handlers/request_handler_spec.rb
- spec/lib/billy/handlers/stub_handler_spec.rb
- spec/lib/billy/proxy_request_stub_spec.rb
- spec/lib/billy/resource_utils_spec.rb
- spec/lib/proxy_spec.rb
- spec/spec_helper.rb
- spec/support/test_server.rb
Mainly removing hash rockets, spacing adjustments, and single quotes over double quotes.
> Rubocop code cleanup

- Gemfile.lock
- lib/billy/proxy.rb
- lib/billy/proxy_connection.rb
I'm proposing this PR in order to avoid `instance variable not initialized` warnings
> Fix "not initialized" warnings

- CHANGELOG.md
I noticed this typo and figured I'd send along a fix.
> Change "uninitalized" -> "uninitialized"

- lib/billy.rb
This preserves webkit config when creating the webkit_billy driver.
> Billy config and Capybara::Webkit config compatibility

- lib/billy/handlers/proxy_handler.rb
This outputs the request method with the proxy returns an error. This is useful for debugging if the request was OPTIONS or POST,GET
No specs were harmed during this edit :)
> output the request method when proxy returns an error

- README.md
- examples/post_api.html
- spec/features/examples/post_api_spec.rb
The README mentions:
"The cache works with all types of requests and will distinguish between different POST requests to the same URL."
But this isn't correct (as far as I understand it).
So, I created an integration spec that shows the method needs to be set explicitly when stubbing out the proxy. Also, I gave and example in the readme. 
This stumped me for a while. Hopefully, it helps.
> explicit method is required when stubbing out posts

- lib/billy.rb
I'm not sure why, but the changes in #130 no longer ignores SSL errors for `Capybara::Webkit::Driver`. And as far as I can tell it completely breaks SSL when using the WebKit driver. (Leading to a long and draining debugging process for me yesterday.) You can easily confirm this by adjusting the test suite to run with the WebKit driver instead:
```diff
index 5961b29..a5f2482 100644
--- a/spec/spec_helper.rb
+++ b/spec/spec_helper.rb
@@ -6,7 +6,7 @@ require 'rack'
require 'logger'
Capybara.app = Rack::Directory.new(File.expand_path('../../examples', __FILE__))
-Capybara.javascript_driver = :poltergeist_billy
+Capybara.javascript_driver = :webkit_billy
Billy.configure do |config|
config.logger = Logger.new(File.expand_path('../../log/test.log', __FILE__))
```
Would greatly appreciate a bug …
> Change WebKit driver to ignore SSL errors.

- README.md
- examples/preflight_request.html
- spec/features/examples/preflight_request_spec.rb
- spec/lib/billy/proxy_request_stub_spec.rb
- spec/lib/proxy_spec.rb
I was having trouble stubbing out OPTIONS requests. Here are some specs that prove it works.
> Add documentation and specs for stubbing out options requests

- .travis.yml
- README.md
- lib/billy/cache.rb
- lib/billy/config.rb
- lib/billy/handlers/request_handler.rb
- lib/tasks/billy.rake
- spec/lib/billy/cache_spec.rb
- spec/lib/billy/handlers/request_handler_spec.rb
This adds a config option `cache_request_body_methods`, allow you to specify the HTTP methods for which you would like the cache to distinguish between requests with different bodies. Previously, this only applied to POST requests, but PATCH and PUT requests also often have different bodies that it's useful to distinguish between when recording requests and responses in the cache. The default value remains `['post']` so the functionality when the option is not set should not change.
I also added a before_install step to travis.yml to update bundler and fix the `undefined method spec for NilClass` error which was preventing gems from installing sometimes, it looks like this might have been the issue: https://github.com/bundler/bundler/issues/3560.
> Support distinguishing non-POST requests in cache based on request body

- README.md
- lib/billy/config.rb
- lib/billy/handlers/cache_handler.rb
- spec/lib/billy/handlers/cache_handler_spec.rb
Adds support for an after_cache_handle_request callback. Useful for things like manipulating CORs headers, result of this issue: https://github.com/oesmith/puffing-billy/issues/139
> Add optional after_cache_handles_request callback for manipulating cached responses

- README.md
"New" expectation syntax gets rid of the following message when running the example:
```shell
DEPRECATION: Using `should` from rspec-expectations' old `:should` syntax without 
explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly 
enable `:should` with `config.expect_with(:rspec) { |c| c.syntax = :should }` instead. 
Called from /cucumber/features/step_definitions/test.rb:8:in `block in <top (required)>'.
```
> Remove rspec-expectations deprecation warning for README example

- .travis.yml
This solves (supposedly) the random build failures in Travis.
Merge only after reviewing the build process of Travis.
> Upgrade PhantomJS to 2.0 to fix the Travis build process

- lib/billy/handlers/proxy_handler.rb
- lib/billy/proxy_connection.rb
- spec/lib/billy/proxy_connection_spec.rb
I had an issue where gzipped CSS/JS assets were not accepted by the browser through the Puffing Billy proxy because the headers were tampered with. Since Puffing Billy forces the response content encoding to `binary`, the `Content-Encoding` and `Content-Length` headers should be updated, but they aren't. Later on, in the EventMachine::HttpResponse class, another `Content-Length` header is added which has the right value. Which means at that moment there are two headers which shouldn't be there: the original `Content-Length` header and the `Content-Encoding` header which still points to `gzip`. See https://github.com/eventmachine/evma_httpserver/blob/master/lib/evma_httpserver/response.rb#L194
Tests are fine, but I don't know if it breaks anything else. I would prefer fixing it on the …
> Fix response headers by anticipating EventMachine::HttpResponse behavior

- lib/billy/browsers/capybara.rb
reverts lib/billy/browsers/capybara.rb to correctly rescue from LoadError
> Rescue LoadErrors during driver registration

- lib/billy/cache.rb
- lib/billy/handlers/proxy_handler.rb
**Fixes the particular problem with scopes**
_Clean run, cache folder is empty_
1. cache.scope_to 'first'
2. make request, it comes to EM defers queue
3. cache.scope_to 'second'
4. EM processes the request, and caches the response within 'second' scope
_Then the test runs again_
1. cache.scope_to 'first'
2. make request, CacheHandler can't find already cached response within 'first' scope
3. cache.scope_to 'second'
4. EM processes the request and rewrites the cache within 'second' scope
> Fix floating scopes

- README.md
- lib/billy/config.rb
- lib/billy/handlers/cache_handler.rb
- spec/lib/billy/handlers/cache_handler_spec.rb
We were trying to stub out requests from a third party library which we cannot modify. The library uses JSONP requests with `jsoncallback` as the name of the callback param.
To address this, this PR allows a custom callback name to be passed into the Billy config and keeps the default callback name as `callback`.
> allow the dynamic jsonp callback name to be configured

- README.md
- lib/billy/config.rb
- lib/billy/handlers/cache_handler.rb
- spec/lib/billy/handlers/cache_handler_spec.rb
We use puffing-billy to record front-end requests to our microservices and later serve them from cache, but sometimes we hit race condition bugs with front-end requests not ordered correctly (e.g. emit event that is not yet listened). These issues are rarely caught during development because all microservices are using localhost so requests are super fast and they are not caught during automated tests because cached responses are instant. However, in production they happen often since there is DNS lookup, real requests, etc.
This PR allows to simulate network delays before responding from cache. It's very simple and delays are not configurable but it has proven to catch/reveal such bugs during automated tests execution.
If this is something you'd like to merge in, I'd be glad to address …
> Allow to simulate network delays when responding from cache

- .travis.yml
- lib/billy/browsers/capybara.rb
:args or :switches has been deprecated. The recommended approach is to
use Selenium::WebDriver::Chrome::Options#add_argument instead
> fix selenium webdriver deprecation warning

- puffing-billy.gemspec
I'm using Puffing Billy in conjunction with Sauce Connect (and a PAC file when launching Sauce Connect) to run tests in Sauce Labs. After updating Puffing Billy to `0.11.0` recently, I was running into issues with this setup where any request would result in a 502 Bad Gateway error in the browser, because of `connection error: Connection refused` from Sauce Connect. I rolled Puffing Billy back to an earlier version that worked for this configuration to verify that it was an issue caused by the Puffing Billy update.
Using `git bisect` I tracked the root cause to the changes to the gemspec in [this commit](https://github.com/oesmith/puffing-billy/commit/e7839a00b5c86a4641efb51847890cf18715ca59). I was able to work out that the problem only exists when updating `eventmachine` past version …
> Prevent eventmachine from installing 1.2.x

- lib/billy/cache.rb
This allows `puffing_billy` to follow symlinks.
This is helpful for infrastructures that support certain mocks being shared.
> Check if cache_file is a symlink, and if so, return the linked file

- puffing-billy.gemspec
An unintended side-affect of my last PR #206 was that PROXY requests to HTTP/2 resources traversing Puffing Billy would fail. I found that updating `eventmachine` to a version >= 1.2 would fix that issue.
As an extra note: the 502 Bad Gateway responses I was seeing in #206 were actually an issue with configuring Puffing Billy. I did some digging with Wireshark and found that the requests were all getting through the Sauce Connect tunnel, but Puffing Billy was actually rejecting them. I had set the `proxy_port` to a specific number, but left `proxy_host` as its default of `localhost`. What I needed to do was specifically set that to `127.0.0.1` to force it to use IPv4 - problem solved.
#206 
Medium
- Gem bump may have unintended side-effects
> Bump eventmachine version to support loading HTTP/2 resources

- .travis.yml
- README.md
- lib/billy/browsers/watir.rb
- lib/billy/handlers/request_handler.rb
- lib/billy/handlers/stub_handler.rb
- lib/billy/proxy.rb
- puffing-billy.gemspec
- spec/lib/billy/handlers/stub_handler_spec.rb
In some test cases, it is required to dynamically decide which requests should be stubbed, and which not. Using `proxy.reset` is not the best way to it since it provides no control over which stubs are to be removed.
This PR adds a new method: `proxy.unstub`, which acts as a reverse to `proxy.stub`, and removes only a single stub.
See `spec/lib/billy/handlers/stub_handler_spec.rb:66` for examples.
Additionally, this PR removes dependency `watir-webdriver`. That gem was outdated, deprecated and in fact already has already been removed from GitHub. It is now a part of `watir` gem, and this one has been added instead.
`watir-webdriver` was throwing a ton of warnings (Fixnum) and an exception on just `require 'watir-webdriver'` making work on this change impossible.
> Add #unstub method, replace deprecated watir-webdriver with watir

- lib/billy/handlers/request_handler.rb
- spec/lib/billy/handlers/request_handler_spec.rb
This fixes an issue where when an underlying error happens, say someone is using VCR for client side stubs and it raises an error, the web process hangs due to the proxy crashing. This catches any unhandled standard error and returns it as part of the error hash from the request. This will result in the error message being written to the log and allowing the proxy to continue running.
> Catch unhandled request handler errors

- README.md
- lib/billy/proxy_request_stub.rb
- spec/lib/billy/proxy_request_stub_spec.rb
**- What is it good for?**
This update ships the possibility to intercept requests and responses on the proxy stub method. This is quite handy when you want to modify ugly client requests or just want to modify the response body on certain requests. In the test suite where this feature was implemented, we wanted to intercept responses with a content disposition header and save their content to file. (aka file download) This is required due to the [some bugs on Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=819220) atm. (Cant save PDF files on headless, crash on new tabs of PDF files on non-headless)
**- What I did**
I added a new `pass_request` method to the `ProxyRequestStub` class which makes use of the existing functionality of the proxy handler. Furthermore, I switched …
> Allow request/response interception on stubs

- lib/billy/handlers/request_handler.rb
- lib/billy/handlers/stub_handler.rb
- lib/billy/proxy.rb
- spec/lib/billy/handlers/request_handler_spec.rb
- spec/lib/billy/handlers/stub_handler_spec.rb
- spec/lib/proxy_spec.rb
It would be nice to expose the currently registered stubbed instances via puffing billy.
This will allow for developers to learn which stubs were not correctly called, or are dead:
```ruby
Billy.configure do |c|
c.record_stub_requests = true
end
config.after(:example, type: :feature) do
unused_stubs = proxy.stubs.select { |stub| stub.requests.empty? }
expect(unused_proxy_stubs).to be_empty, "expected all stubs to be used, however no requests were received for #{unused_proxy_stubs}"
end
```
> Expose stub instances via puffing billy

- lib/billy/init/rspec.rb
- lib/billy/proxy.rb
Let's explicitly shutdown event machine after our test suite has run.
Closes https://github.com/oesmith/puffing-billy/issues/237
> Add after suite stop hook for event machine

- README.md
- lib/billy.rb
- lib/billy/proxy_request_stub.rb
- spec/features/examples/tumblr_api_spec.rb
- spec/lib/billy/proxy_request_stub_spec.rb
See: https://github.com/oesmith/puffing-billy/issues/241#issuecomment-385370968
> Fix scope breaking change of request/response interception. (#241)

- lib/billy/proxy.rb
Hello,
Looks like `Exception`s are allowed to not have backtrace available
Trying to `join()` on nil terminates puffing billy so I think it's feasible to check whether exception has backtrace before atttempting to print it 
I had some problems with `puffing-billy` terminating because of exception in main_loop thread what caused it to terminate and as a consequence -  following tests in suite to fail because proxy has just died so no requests passed through it would receive a response
> Don't  attempt to print backtrace when it's not available (EM event handler)

- README.md
Cucumber instructions were already included in README.MD. This adds similar instructions for RSPEC to maintain parity between the two.
> Update README to include making scenario spec-specific folders via Rspec

- README.md
- lib/billy/proxy_request_stub.rb
- spec/lib/billy/proxy_request_stub_spec.rb
Add a new value `all` to proxy stub handler's `method` option that will intercept all requests regardless of the method.
> Allow intercepting requests with any method

- lib/billy/handlers/proxy_handler.rb
I was experiencing the same issue as in https://github.com/oesmith/puffing-billy/issues/204 which seems to be due to puffing billy being unable to decode a response.
I eventually stumbled across a PR that addresses this issue (https://github.com/oesmith/puffing-billy/pull/167) by setting the `accept-encoding` header to a blank string instead of deleting it. According to @damned, the root cause is the `em-http-request` library which sets the `accept-encoding` header if it's not present. Once I made this change, the `Content-decoder` error disappeared.
> Accept all encodings

- lib/billy/browsers/capybara.rb
Chrome headless driver registration along with time-out bug fix for ChromeDriver v74.0.3729.6 in headless mode.
> Add driver registration for chrome headless

- README.md
It looks like the `:selenium_chrome_headless_billy` driver was added to this project recently, but not documented yet in the README.
> Add selenium_chrome_headless_billy to README

- README.md
- lib/billy/browsers/capybara.rb
The `selenium_billy` driver doesn't appear to support headless mode, and also (though unrelated) throws a `Selenium [DEPRECATION] :profile is deprecated. Use Selenium::WebDriver::Firefox::Options#profile= instead.` warning.
I've simply refactored the `selenium_billy` driver so that we're no longer using the deprecated method of setting a profile, and then added a `selenium_headless_billy` driver with headless support.
> Add Selenium headless driver

- README.md
- lib/billy/config.rb
- lib/billy/handlers/proxy_handler.rb
- spec/lib/billy/handlers/proxy_handler_spec.rb
- spec/lib/proxy_spec.rb
Currently, for a URL to be cacheable, it must have a cacheable HTTP response code and:
- Must be a non-whitelisted URL, or
- Must be a blacklisted path
The problem with this is that sometimes you may want to force a whitelisted host to also be cacheable. For example, in one application I'm working on, I'd like to block _all_ external requests using `c.non_whitelisted_requests_disabled`, but allow specific hosts to be cached so that I can use Puffing-Billy as I would VCR.
Logically, when using `c.non_whitelisted_requests_disabled` only whitelisted requests are enabled. Unfortunately, however, whitelisted URLs are never cached, so I have two options:
1)  Set `c.non_whitelisted_requests_disabled` to `false` and cache _all_ requests, OR
2)  Abandon my plan to use Puffing-billy as I would VCR, …
> Add `cache_whitelist` config option

- examples/tumblr_api_https.html
- lib/billy/browsers/capybara.rb
- spec/lib/billy/browsers/capybara_spec.rb
After upgrading Chrome to version 79, our app's test suite started producing a steady stream of warnings like the following one:
```
140361933186816:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:s3_pkt.c:1487:SSL alert number 46
```
Additionally, all actual HTTPS requests fail, which, in turn, fails our tests expecting those requests to be successful.
I'm not sure what exact change in Chrome triggered the warning that wasn't showing before, but the only two ways to remove it are:
* Add the `ignore-certificate-errors` flag to Chrome
* Stop using Puffing Billy
Since not using Puffing Billy is not really an option, we can only ask Chrome to ignore all certificate errors. This clears the warnings and makes the tests expecting HTTPS requests to succeed to pass. …
> Ignore certificate errors in Chrome

- puffing-billy.gemspec
- spec/lib/proxy_spec.rb
This fixes the specs failure as `Faraday::Error::ConnectionFailed` has been deprecated, and later removed in 'faraday' v1.0.0, in favor of `Faraday::ConnectionFailed`
> Update min 'faraday' gem version required

- README.md
- lib/billy/config.rb
- lib/billy/handlers/proxy_handler.rb
Resolves #293 
Also note that this doesn't make these warnings
```
[WARNING; em-http-request] TLS hostname validation is disabled (use 'tls: {verify_peer: true}'), see CVE-2020-13482 and https://github.com/igrigorik/em-http-request/issues/339 for details
```
go away unless this is merged: https://github.com/igrigorik/em-http-request/pull/341
OR ```verify_peer: true``` is used.
> Make verify_peer configurable and default it to false

- lib/billy/ssl/certificate_helpers.rb
When running puffing-billy in a parallel test environment (for instance, in Rails 6), frequent crashes occur, with errors like the following:
```
123145443577856:error:0909006C:PEM routines:get_name:no start line:crypto/pem/pem_lib.c:745:Expecting: TRUSTED CERTIFICATE
123145443577856:error:140DC009:SSL routines:use_certificate_chain_file:PEM lib:ssl/ssl_rsa.c:622:
Assertion failed: (e > 0), function SslContext_t, file ssl.cpp, line 203.
```
```
123145562779648:error:0909006C:PEM routines:get_name:no start line:crypto/pem/pem_lib.c:745:Expecting: ANY PRIVATE KEY
123145562779648:error:140B0009:SSL routines:SSL_CTX_use_PrivateKey_file:PEM lib:ssl/ssl_rsa.c:556:
Assertion failed: (e > 0), function SslContext_t, file ssl.cpp, line 196.
```
These errors occur because parallel puffing-billy …
> Include pid in names of temporary files

- lib/billy/proxy.rb
While waiting for shutdown, the proxy attempts to connect to the event machine TCP socket in a loop until the connection fails to be made.
There's a small possibility here that the connection is established but the socket is closed by the remote before the poller closes it, in which case we get an `Errno::ECONNRESET` exception that isn't currently handled.
I think this error also indicates that we've shut down successfully, so this PR adds it to the existing rescue.
I _think_ it's safe to conclude that EM has shut down as a result of this error, but there might be other explanations for the reset; would we prefer to go round the loop again in this case and wait for one of the other errors?
Also, I didn't see an obvious place to add a test for this behaviour, and concluded that since it's …
> Rescue Errno::ECONNRESET in shutdown phase

- lib/billy/browsers/capybara.rb
- puffing-billy.gemspec
This PR introduces two changes, the first one is in the gemspec file where the gem generated included all files, but now it will require only the needed ones.
@oesmith could you confirm that this is correct? Do you need the binary to be included? You don't mention it in the README so I guess it is not for the gem.
Another change in the gemspec is to bump the minimum required version to 3.150.0 where `assume_untrusted_certificate_issuer` was [removed](https://github.com/SeleniumHQ/selenium/commit/e3541d6aa8d84fe6c673b984c96c07d1e161facc#diff-7ee189046cdbd95200c1e7f74f56b9ccde5f779876e7df363e44dd1be4f46915) from the firefox profile class.
The last change is in `lib/billy/browsers/capybara.rb`, where I removed `assume_untrusted_certificate_issuer` (I don't know what the alternative is) and …
> Adapt puffing billing to newer versions selenium webdriver

- lib/billy/cache.rb
- lib/billy/handlers/proxy_handler.rb
While debugging general performance/reliability issues in our test suite, I thought I would see what effect disabling Billy's cache had on our test suite. (We don't intentionally use it.) 
So I configured with `cache = false`, but was still surprised to see log entries about calculated cache keys for requests.
It appears ProxyHandler was unconditionally calculating the scope and key, the latter of which seems expensive to perform. 
Admittedly, my understanding of the overall system is minimal, but it _seems_ like this change wouldn't have any unwanted side effects, and skip unused method calls for users who have `cache = false`.
> Only calculate cache scope and key if request is cacheable for performance

- README.md
- lib/billy/browsers/capybara.rb
- lib/billy/config.rb
This PR adds support for a configurable Cuprite driver.
What I mean is that it allows passing additional flags to the driver like that :
```ruby
remote_options = remote_chrome ? { url: REMOTE_CHROME_URL } : {}
Billy.configure do |c|
c.cuprite_options = {
browser_options: remote_chrome ? { 'no-sandbox' => nil } : {},
inspector: true,
js_errors: true,
save_path: File.join(Capybara.save_path, 'downloads'),
window_size: [810, 1080]
}.merge(remote_options)
c.cache = true
end
require 'billy/capybara/cucumber'
Capybara.default_driver =
Capybara.javascript_driver =
Capybara.current_driver = :cuprite_billy
```
This PR also update the `README.md` file in order to explain how to configure a remote Chrome with nice tip about ActionCable taken from …
> Adds a configurable Cuprite driver

- lib/billy/browsers/capybara.rb
The `selenium-webdriver` `headless!` method has been deprecated since version 4.8 (https://github.com/SeleniumHQ/selenium/blob/trunk/rb/CHANGES#L114) and on version 4.11.0 it got removed (https://github.com/SeleniumHQ/selenium/pull/12417)
According to the documentation https://www.selenium.dev/blog/2023/headless-is-going-away/, the new way to run a headless browser is with the `--headless=new` argument.
Fixes https://github.com/oesmith/puffing-billy/issues/332
> Replace deprecated headless! `Selenium::WebDriver::Chrome::Options`

- .github/workflows/ci.yml
- puffing-billy.gemspec
Ruby 2.6 has reached EOL since 2022-04-12. To keep `puffing-billy` moving forward I believe dropping support to EOL versions of Ruby will be necessary.
> Drop Ruby 2.6 support

- lib/billy/browsers/capybara.rb
`driver_otions` → `driver_options`
Just happened to notice this! 😅
> Fix spelling mistake

- .github/workflows/ci.yml
- spec/features/examples/intercept_request_spec.rb
As #342 seems to got stuck. Here's a new attempt:
* remove unsupported Ruby Versions (2.7 and 3.0)
* add Ruby head
* use latest checkout action version
> Update CI test matrix

- .github/workflows/ci.yml
- lib/billy/proxy_connection.rb
Add unary operator to mutable string.
This avoids deprecation warnings when running against ruby 3.4.1 and prepares for later versions (4.0) that will default to `# frozen_string_literal: true`.
Deprecation warning:
```sh
gems/puffing-billy-4.0.0/lib/billy/proxy_connection.rb:33: warning: literal string will be frozen in the future (run with --debug-frozen-string-literal for more information)
```
Example CI with deprecation warnings:
https://app.circleci.com/pipelines/github/ministryofjustice/laa-apply-for-legal-aid/32282/workflows/b137f673-cb4e-4f21-a307-86050bde6e87/jobs/168908/parallel-runs/0?filterBy=ALL
> Fix: handle deprecation warning - add unary operator to mutable string
